#!/bin/sh
# Manage the CrowdSec nginx bouncer at container start.
#
# What it does:
#   1. Renders /etc/crowdsec/bouncers/crowdsec-nginx-bouncer.conf.local from
#      env vars. The bouncer merges .local on top of the shipped .conf, so
#      we only write the user's overrides — upstream defaults survive.
#   2. Symlinks /etc/nginx/crowdsec-include.conf to either the enabled or
#      disabled variant in /usr/share/cs-nginx-bouncer/.
#
# How the user wires it up:
#   - Add ONE line to nginx.conf (inside http {}):
#         include /etc/nginx/crowdsec-include.conf;
#   - Toggle CROWDSEC_BOUNCER_ENABLED at runtime; the include shim flips.

set -eu

BOUNCER_CONF=/etc/crowdsec/bouncers/crowdsec-nginx-bouncer.conf
BOUNCER_LOCAL=/etc/crowdsec/bouncers/crowdsec-nginx-bouncer.conf.local
INCLUDE_SHIM=/etc/nginx/crowdsec-include.conf
INCLUDE_ENABLED=/usr/share/cs-nginx-bouncer/crowdsec-include.conf.enabled
INCLUDE_DISABLED=/usr/share/cs-nginx-bouncer/crowdsec-include.conf.disabled

is_truthy() {
    case "${1:-}" in
        1|true|TRUE|True|yes|YES|on|ON) return 0 ;;
        *) return 1 ;;
    esac
}

mkdir -p "$(dirname "$INCLUDE_SHIM")"

if ! is_truthy "${CROWDSEC_BOUNCER_ENABLED:-false}"; then
    ln -sfn "$INCLUDE_DISABLED" "$INCLUDE_SHIM"
    # Clear any stale .local so an enabled-then-disabled flip doesn't leave
    # a key file pointing at nothing if the user later re-enables manually.
    rm -f "$BOUNCER_LOCAL"
    echo "[bouncer] disabled (CROWDSEC_BOUNCER_ENABLED=false)"
    exit 0
fi

if [ ! -f "$BOUNCER_CONF" ]; then
    echo "[bouncer] $BOUNCER_CONF missing — bouncer assets not installed?" >&2
    exit 1
fi
if [ ! -f "$INCLUDE_ENABLED" ]; then
    echo "[bouncer] $INCLUDE_ENABLED missing — image is broken" >&2
    exit 1
fi

if [ -z "${CROWDSEC_LAPI_URL:-}" ] || [ -z "${CROWDSEC_BOUNCER_API_KEY:-}" ]; then
    echo "[bouncer] CROWDSEC_LAPI_URL and CROWDSEC_BOUNCER_API_KEY must be set" >&2
    exit 1
fi

mkdir -p "$(dirname "$BOUNCER_LOCAL")"

{
    echo "# Generated by render-bouncer-conf.sh at $(date -u +%FT%TZ)"
    echo "# Edit env vars on the container to change; do not edit this file directly."
    echo "API_URL=${CROWDSEC_LAPI_URL}"
    echo "API_KEY=${CROWDSEC_BOUNCER_API_KEY}"
    echo "MODE=${CROWDSEC_MODE:-stream}"
    echo "BAN_TEMPLATE_PATH=${CROWDSEC_BAN_TEMPLATE_PATH:-/var/lib/crowdsec/lua/templates/ban.html}"
    echo "CAPTCHA_TEMPLATE_PATH=${CROWDSEC_CAPTCHA_TEMPLATE_PATH:-/var/lib/crowdsec/lua/templates/captcha.html}"
    [ -n "${CROWDSEC_BOUNCING_ON_TYPE:-}" ]    && echo "BOUNCING_ON_TYPE=${CROWDSEC_BOUNCING_ON_TYPE}"
    [ -n "${CROWDSEC_FALLBACK_REMEDIATION:-}" ] && echo "FALLBACK_REMEDIATION=${CROWDSEC_FALLBACK_REMEDIATION}"
    [ -n "${CROWDSEC_UPDATE_FREQUENCY:-}" ]    && echo "UPDATE_FREQUENCY=${CROWDSEC_UPDATE_FREQUENCY}"
    [ -n "${CROWDSEC_REQUEST_TIMEOUT:-}" ]     && echo "REQUEST_TIMEOUT=${CROWDSEC_REQUEST_TIMEOUT}"
    [ -n "${CROWDSEC_EXCLUDE_LOCATION:-}" ]    && echo "EXCLUDE_LOCATION=${CROWDSEC_EXCLUDE_LOCATION}"
    [ -n "${CROWDSEC_CACHE_EXPIRATION:-}" ]    && echo "CACHE_EXPIRATION=${CROWDSEC_CACHE_EXPIRATION}"
    [ -n "${CROWDSEC_RET_CODE:-}" ]            && echo "RET_CODE=${CROWDSEC_RET_CODE}"
    [ -n "${CROWDSEC_REDIRECT_LOCATION:-}" ]   && echo "REDIRECT_LOCATION=${CROWDSEC_REDIRECT_LOCATION}"
    # Captcha
    [ -n "${CROWDSEC_CAPTCHA_PROVIDER:-}" ]    && echo "CAPTCHA_PROVIDER=${CROWDSEC_CAPTCHA_PROVIDER}"
    [ -n "${CROWDSEC_CAPTCHA_SECRET_KEY:-}" ]  && echo "SECRET_KEY=${CROWDSEC_CAPTCHA_SECRET_KEY}"
    [ -n "${CROWDSEC_CAPTCHA_SITE_KEY:-}" ]    && echo "SITE_KEY=${CROWDSEC_CAPTCHA_SITE_KEY}"
    [ -n "${CROWDSEC_CAPTCHA_EXPIRATION:-}" ]  && echo "CAPTCHA_EXPIRATION=${CROWDSEC_CAPTCHA_EXPIRATION}"
    # AppSec
    if [ -n "${CROWDSEC_APPSEC_URL:-}" ]; then
        echo "APPSEC_URL=${CROWDSEC_APPSEC_URL}"
        [ -n "${CROWDSEC_APPSEC_FAILURE_ACTION:-}" ]       && echo "APPSEC_FAILURE_ACTION=${CROWDSEC_APPSEC_FAILURE_ACTION}"
        [ -n "${CROWDSEC_APPSEC_CONNECT_TIMEOUT:-}" ]      && echo "APPSEC_CONNECT_TIMEOUT=${CROWDSEC_APPSEC_CONNECT_TIMEOUT}"
        [ -n "${CROWDSEC_APPSEC_SEND_TIMEOUT:-}" ]         && echo "APPSEC_SEND_TIMEOUT=${CROWDSEC_APPSEC_SEND_TIMEOUT}"
        [ -n "${CROWDSEC_APPSEC_PROCESS_TIMEOUT:-}" ]      && echo "APPSEC_PROCESS_TIMEOUT=${CROWDSEC_APPSEC_PROCESS_TIMEOUT}"
        [ -n "${CROWDSEC_APPSEC_ALWAYS_SEND:-}" ]          && echo "ALWAYS_SEND_TO_APPSEC=${CROWDSEC_APPSEC_ALWAYS_SEND}"
        [ -n "${CROWDSEC_APPSEC_DROP_UNREADABLE_BODY:-}" ] && echo "APPSEC_DROP_UNREADABLE_BODY=${CROWDSEC_APPSEC_DROP_UNREADABLE_BODY}"
        [ -n "${CROWDSEC_APPSEC_SSL_VERIFY:-}" ]           && echo "SSL_VERIFY=${CROWDSEC_APPSEC_SSL_VERIFY}"
    fi
} > "$BOUNCER_LOCAL"

chmod 640 "$BOUNCER_LOCAL"
ln -sfn "$INCLUDE_ENABLED" "$INCLUDE_SHIM"

echo "[bouncer] enabled (LAPI=$CROWDSEC_LAPI_URL, mode=${CROWDSEC_MODE:-stream}, appsec=${CROWDSEC_APPSEC_URL:-off})"
echo "[bouncer] reminder: nginx.conf must contain   include /etc/nginx/crowdsec-include.conf;   inside http {}"
